import { Poppins } from "next/font/google";
import "@styles/globals.css";
import MusicContextProvider from "./libs/context/musicContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Melodify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <MusicContextProvider>{children}</MusicContextProvider>
      </body>
    </html>
  );
}
